#!/bin/bash
docker container kill $(docker ps | grep "vpn-server" | awk '{ print $1 }')
docker rm $(docker ps -a | grep "vpn-server" | awk '{ print $1 }')
docker build --no-cache -t vpn-server .
docker run --name vpn-server --restart=always --network=host -p 500:500/udp -p 4500:4500/udp -d -it --privileged --env-file l2tp.env -v /lib/modules:/lib/modules vpn-server